export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_CHECKED = "LOGIN_CHECKED";

export const ACCESS_DENIED = "ACCESS_DENIED";
export const ACCESS_GRANTED = "ACCESS_GRANTED";
export const LOGOUT_SESSION = "LOGOUT_SESSION";
export const GENERAL_FAILURE = "GENERAL_FAILURE";

export const RETRIEVE_USR_DEVICES = "RETRIEVE_USR_DEVICES";
export const RETRIEVE_ALL_DEVICES = "RETRIEVE_ALL_DEVICES";

export const SET_REGISTER_DEVICES = "SET_REGISTER_DEVICES";
export const SET_REGISTER_CONTEXT = "SET_REGISTER_CONTEXT";
export const SET_REGISTER_CURRENT = "SET_REGISTER_CURRENT";
export const SET_REGISTER_OPTIONS = "SET_REGISTER_OPTIONS";
export const CLR_REGISTER_REDUCER = "CLR_REGISTER_REDUCER";

export const SET_VALIDATE_DEVICES = "SET_VALIDATE_DEVICES";
export const SET_VALIDATE_CURRENT = "SET_VALIDATE_CURRENT";
export const SET_VALIDATE_OPTIONS = "SET_VALIDATE_OPTIONS";
